### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by stakx** [castleproject/NVelocity#3]
### Current situation:

* This repository's `README.me` says:

   > More information about NVelocity can be found at http://www.castleproject.org/

* On the website, NVelocity is not (yet?) listed as an active project. Knowing that NVelocity used to be part of MonoRail, that's where I'm taking a look next, only to find that the MonoRail V2 documentation is [back on GitHub](https://github.com/castleproject-deprecated/MonoRail/blob/master/MR2/docs/README.md)!

* And there it is that we finally find the [documentation on NVelocity](https://github.com/castleproject-deprecated/MonoRail/blob/master/MR2/docs/nvelocity.md), however it is written in the context of MonoRail, which probably no longer matches the current situation / use case?

### Suggestions:

* Add a `docs` directory to this repository, which is where the documentation will live for the time being.

* Use https://github.com/castleproject-deprecated/MonoRail/blob/master/MR2/docs/nvelocity.md as a template for some new documentation.

* Update the repository's main `README.md` to link to `docs/README.md` instead of the website.

* Update the website: Add NVelocity as an active project (https://github.com/castleproject/castleproject.github.io/pull/4 is a first small step in that direction, but by itself not sufficient) on the website and have its documentation link point to `docs/README.md` here.

**Comment by jonorossi** [comment]
@phillip-haydon did you want to have a look at this one?

**Comment by jonorossi** [comment]
> Also what's remaining for us to get it onto nuget?

Probably nothing much. I think I just need to add a NuGet.org API key into AppVeyor.

If you take a look at the Castle Core closed issues you'll see I've been creating issues to prepare for the release to make sure if anyone on the team or external contributor wants to jump in before a release they can, I feel it makes things explicit for everyone following along. Feel free to create an issue (named maybe "Release 1.2.0") and we can get underway.

**Comment by phillip-haydon** [comment]
New issue for a release is done. 

And docs are merged, can this issue be closed or is there anything else we need?

**Comment by jonorossi** [comment]
Looks good for now.
