### ISSUE TITLE
Release 1.2.0

### ISSUE THREAD

**Issue by phillip-haydon** [castleproject/NVelocity#9]
Initial release of rebooted NVelocity. The primary driving force of this release is to bring support for .NET Standard 2.0 for people who still use NVelocity, and those who wish to use it in new projects.

@castleproject/committers your input?

**Comment by jonorossi** [comment]
@phillip-haydon Sorry for the delay replying. We need to:

- ~~Add NuGet.org API key to AppVeyor build~~ Done
- Set up auto publishing nuget package to NuGet.org using `NUGET_API_KEY` ([see Castle Core](https://github.com/castleproject/Core/blob/f84d4fcebdc66b859c321b2eee5434aa41df19f5/appveyor.yml#L28-L34))
- Update the changelog with 1.2.0

**Comment by emagers** [comment]
Any update on the release date?

**Comment by phillip-haydon** [comment]
Sorry! My baby was born and so I’ve been busy, currently in Taiwan with the rest of the family and don’t own a laptop at the moment :(

I’ll try get this finished when I’m back next month. Unless someone else wants to get this over the line.

**Comment by jonorossi** [comment]
Thanks Eric for getting the AppVeyor script fixed.

For some reason the unit tests now fail in the Linux build, we need to fix that before releasing.

**Comment by jonorossi** [comment]
@phillip-haydon congrats on the baby 🎉, I hope everyone is well.

**Comment by phillip-haydon** [comment]
![05ce5c42-4441-4de0-91ce-29d5a727d25a](https://user-images.githubusercontent.com/895629/49849273-b471f100-fe13-11e8-8aa2-33a48c8db022.jpeg)

Azabeth says hello.

I can take a look at the unit tests on Monday onward. I’m back in singapore just need to catch up on things first.

**Comment by emagers** [comment]
Congratulations, Phillip!

Is there anyway for me to see the test errors, or get any information on the test environment (like OS version, what dotnet SDK is installed)? I just ran the build and tests locally on Ubuntu 16.04 with the latest dotnetcore 2.2 SDK and it was successful.

**Comment by jonorossi** [comment]
@emagers yep, you can navigate to the build details for master from the branches page:
https://github.com/castleproject/NVelocity/branches

**Comment by jonorossi** [comment]
The problem looks culture related:

```
ht = new Hashtable(StringComparer.CurrentCultureIgnoreCase);
```

Not sure if AppVeyor has changed the culture the machines are configured with. Changing our test to `StringComparer.OrdinalIgnoreCase` will probably fix the problem.

**Comment by emagers** [comment]
@jonorossi Is there a way to test on AppVeyor without merging into master? I can make that change but would like to test before opening a PR, and since it's already not failing locally I can't test this solves anything.

**Comment by jonorossi** [comment]
> Is there a way to test on AppVeyor without merging into master? I can make that change but would like to test before opening a PR

All pull requests are built, you'll see the build status shown at the bottom. Or you could create your own AppVeyor account against your fork. I'd just create a pull request.

**Comment by emagers** [comment]
Haha okay, I guess I missed it when I opened my last PR. The build status isn't normally so hidden

**Comment by emagers** [comment]
I opened a new PR which fixes the failing test cases

**Comment by jonorossi** [comment]
- Tagged [`v1.2.0`](https://github.com/castleproject/NVelocity/releases/tag/v1.2.0)
- Confirmed successfully pushed to nuget.org
- [Tweeted](https://twitter.com/castleproject/status/1074631186268311557)

I've also logged #13 and #14 for someone to look at, no rush.

Thanks guys, sorry for being so slow getting this released.
